language: android

android:
  components:
    - build-tools-19.0.0
    - build-tools-22.0.1
    - android-22

script:
  - ./gradlew check --stacktrace

sudo: false

cache:
  directories:
    - $HOME/.gradle